server:
  port: 9191

spring:
  datasource:
    url: jdbc:oracle:thin:@futsalonboot_high?TNS_ADMIN=./src/main/resources/Wallet_futsalonboot/
    username: ADMIN
    password: '!Afutsalon12'
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #     show_sql: true
        format_sql: true

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: { YOUR_GMAIL_ADDRESS }
    password: { YOUR_GMAIL_PASSWORD }
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            protocols: TLSv1.2
          starttls:
            enable: true
        debug: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

